"""Report endpoints."""
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import PlainTextResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.deps import require_auth
from app.db.session import get_db
from app.models.user import User
from app.schemas.report import ReportGenerateRequest, ReportResponse

router = APIRouter()


DEFAULT_MARKDOWN_REPORT = """# 🔐 SentinelAI Security Audit Report

**Generated:** 2024-01-01T00:00:00Z
**Security Score:** 65/100
**Risk Level:** HIGH

---

## 📊 Executive Summary

This report contains the results of an automated security audit conducted by SentinelAI.

---

## 📈 Statistics

- **Total Vulnerabilities:** 1
- **Critical:** 1
- **High:** 0
- **Medium:** 0
- **Low:** 0
- **Info:** 0

---

## 🔴 Vulnerability Details

### 🔴 Reentrancy Vulnerability

**Severity:** CRITICAL | **Category:** reentrancy | **File:** contract.rs

The withdraw function is vulnerable to reentrancy attacks because it sends XLM before updating the state.

**Vulnerable Code:**
```rust
function withdraw() external {
    (bool success,) = msg.sender.call{value: balance}('');
    require(success);
    balance = 0;
}
```

**Fixed Code:**
```rust
function withdraw() external nonReentrant {
    uint256 amount = balance;
    balance = 0;
    (bool success,) = msg.sender.call{value: amount}('');
    require(success);
}
```

---

## ⛽ Gas Analysis

**Overall Grade:** B

---

## 📝 Recommendations

### Soroban Authorization

Use Stellar authorization framework to prevent reentrancy attacks.

---

*Report generated by SentinelAI - AI-Powered Web3 Security Platform*
"""


@router.post("/generate", response_model=ReportResponse)
async def generate_report(
    request: ReportGenerateRequest,
    current_user: User = Depends(require_auth),
):
    """Generate an audit report."""
    now = datetime.now(timezone.utc).isoformat()
    report_id = f"report_{int(datetime.now(timezone.utc).timestamp())}"

    return ReportResponse(
        id=report_id,
        auditId=request.auditId,
        userId=str(current_user.id),
        contractId="contract_001",
        format=request.format,
        title="Security Audit Report",
        summary="HIGH risk - 1 critical vulnerability found",
        hash="sha256_abc123",
        ipfsHash=None,
        ipfsUri=None,
        txHash=None,
        generatedBy="SentinelAI Report Generator v1.0.0",
        createdAt=now,
    )


@router.get("/", response_model=list[ReportResponse])
async def list_reports(
    current_user: User = Depends(require_auth),
):
    """List all reports for the current user."""
    return []


@router.get("/{report_id}", response_model=ReportResponse)
async def get_report(
    report_id: str,
    current_user: User = Depends(require_auth),
):
    """Get a specific report."""
    now = datetime.now(timezone.utc).isoformat()
    return ReportResponse(
        id=report_id,
        auditId="audit_001",
        userId=str(current_user.id),
        contractId="contract_001",
        format="markdown",
        title="Security Audit Report",
        summary="HIGH risk",
        hash="sha256_abc123",
        generatedBy="SentinelAI",
        createdAt=now,
    )


@router.get("/{report_id}/export")
async def export_report(
    report_id: str,
    format: str = "markdown",
    current_user: User = Depends(require_auth),
):
    """Export a report in the specified format."""
    if format == "markdown":
        return PlainTextResponse(
            content=DEFAULT_MARKDOWN_REPORT,
            media_type="text/markdown",
        )
    elif format == "json":
        return {"report": DEFAULT_MARKDOWN_REPORT}
    else:
        raise HTTPException(status_code=400, detail="Unsupported format")
