import type { AuditResult, Vulnerability } from "@sentinelai/shared";

export function generateMarkdownReport(audit: AuditResult): string {
  const lines: string[] = [];

  lines.push("# 🔐 SentinelAI Security Audit Report");
  lines.push("");
  lines.push(`**Generated:** ${new Date().toISOString()}`);
  lines.push(`**Security Score:** ${audit.securityScore}/100`);
  lines.push(`**Risk Level:** ${audit.summary.overallRisk}`);
  lines.push("");

  lines.push("## 📊 Executive Summary");
  lines.push("");
  lines.push(
    audit.aiInsights?.summary.executiveSummary ??
      `This report contains the results of an automated security audit conducted by SentinelAI. ${audit.summary.totalVulnerabilities} vulnerabilities were identified.`,
  );
  lines.push("");

  lines.push("## 📈 Statistics");
  lines.push("");
  lines.push(`- **Total Vulnerabilities:** ${audit.summary.totalVulnerabilities}`);
  lines.push(`- **Critical:** ${audit.summary.bySeverity.CRITICAL ?? 0}`);
  lines.push(`- **High:** ${audit.summary.bySeverity.HIGH ?? 0}`);
  lines.push(`- **Medium:** ${audit.summary.bySeverity.MEDIUM ?? 0}`);
  lines.push(`- **Low:** ${audit.summary.bySeverity.LOW ?? 0}`);
  lines.push(`- **Info:** ${audit.summary.bySeverity.INFO ?? 0}`);
  lines.push(`- **Gas Optimizations:** ${audit.summary.bySeverity.GAS ?? 0}`);
  lines.push("");

  lines.push("---");
  lines.push("");
  lines.push("## 🔴 Vulnerability Details");
  lines.push("");

  if (audit.vulnerabilities.length === 0) {
    lines.push("✅ No vulnerabilities found.");
    lines.push("");
  } else {
    for (const vuln of audit.vulnerabilities) {
      lines.push(formatVulnerabilitySection(vuln));
      lines.push("---");
      lines.push("");
    }
  }

  lines.push("## ⛽ Gas Analysis");
  lines.push("");
  if (audit.gasAnalysis) {
    lines.push(`**Overall Grade:** ${audit.gasAnalysis.overallGrade}`);
    lines.push(`**Total Gas Used:** ${audit.gasAnalysis.totalGasUsed.toLocaleString()}`);
    lines.push("");
    for (const opt of audit.gasAnalysis.optimizations) {
      lines.push(formatGasOptimization(opt));
    }
  }
  lines.push("");

  if (audit.aiInsights) {
    lines.push("## 🤖 AI Insights");
    lines.push("");
    lines.push(`> ${audit.aiInsights.summary.riskAssessment}`);
    lines.push("");
    lines.push("### Key Findings");
    for (const finding of audit.aiInsights.summary.keyFindings) {
      lines.push(`- ${finding}`);
    }
    lines.push("");
  }

  lines.push("## 📝 Recommendations");
  lines.push("");
  for (const rec of audit.recommendations.slice(0, 5)) {
    lines.push(`### ${rec.title}`);
    lines.push("");
    lines.push(rec.description);
    lines.push("");
    if (rec.fixedCodeSnippet) {
      lines.push("**Fixed Code:**");
      lines.push("```rust");
      lines.push(rec.fixedCodeSnippet);
      lines.push("```");
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("");
  lines.push("*Report generated by SentinelAI - AI-Powered Web3 Security Platform*");

  return lines.join("\n");
}

export function generateJsonReport(audit: AuditResult): string {
  return JSON.stringify(
    {
      reportType: "SentinelAI Security Audit",
      generatedAt: new Date().toISOString(),
      securityScore: audit.securityScore,
      riskLevel: audit.summary.overallRisk,
      statistics: audit.summary,
      vulnerabilities: audit.vulnerabilities,
      gasAnalysis: audit.gasAnalysis,
      recommendations: audit.recommendations,
      aiInsights: audit.aiInsights,
    },
    null,
    2,
  );
}

function formatVulnerabilitySection(vuln: Vulnerability): string {
  const severityEmoji: Record<string, string> = {
    CRITICAL: "🔴",
    HIGH: "🟠",
    MEDIUM: "🟡",
    LOW: "🔵",
    INFO: "⚪",
    GAS: "🟣",
  };

  const emoji = severityEmoji[vuln.severity] ?? "⚪";

  let section = "";
  section += `### ${emoji} ${vuln.title}\n`;
  section += "\n";
  section += `**Severity:** ${vuln.severity} | **Category:** ${vuln.category} | **File:** ${vuln.fileName}\n`;
  if (vuln.lineNumbers.length > 0) {
    section += `**Lines:** ${vuln.lineNumbers.join(", ")}\n`;
  }
  if (vuln.cvssScore) {
    section += `**CVSS Score:** ${vuln.cvssScore}\n`;
  }
  section += "\n";
  section += `${vuln.description}\n`;
  section += "\n";
  section += "**Vulnerable Code:**\n";
  section += "```rust\n";
  section += `${vuln.vulnerableCode}\n`;
  section += "```\n";
  section += "\n";
  if (vuln.fixedCode) {
    section += "**Fixed Code:**\n";
    section += "```rust\n";
    section += `${vuln.fixedCode}\n`;
    section += "```\n";
    section += "\n";
  }
  if (vuln.references.length > 0) {
    section += "**References:**\n";
    for (const ref of vuln.references) {
      section += `- ${ref}\n`;
    }
    section += "\n";
  }

  return section;
}

function formatGasOptimization(opt: {
  title: string;
  description: string;
  estimatedSavings: number;
  difficulty: string;
}): string {
  return `#### ${opt.title}
${opt.description}

- **Estimated Savings:** ${opt.estimatedSavings.toLocaleString()} gas
- **Difficulty:** ${opt.difficulty}
`;
}
